# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  default_filter_set_settings:
    format: webp
  filter_sets:
    cache: ~
    my_thumb:
      quality: 100
      format: webp
      filters:
        thumbnail: { size: [600, 600], mode: outbound }
